version: "3.6"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  webapp:
    build:
      context: .
    image: direct-upload
    ports:
      - "80"
    volumes:
      - .:/home/app/webapp
    environment:
      - RAILS_ENV=development
      - PASSENGER_APP_ENV=development
      - RACK_ENV=development
      - VIRTUAL_HOST=direct-upload.local
